### ISSUE TITLE
Mod Info

### ISSUE THREAD

**Issue by Mishi04** [WarriorCrystal/Huzuniplus-2#3]
Ni puta idea si ustedes usan los issues para sugerencias pero vengo a decir q cambien la foto del pelado con el + en la info del mod 
aqui una foto para q veas a lo q me refiero 
![2021-06-25_11 13 38](https://user-images.githubusercontent.com/69492405/123437979-a1c10100-d5a6-11eb-8208-98cb997f0353.png)

**Comment by Mapeadoh** [comment]
yo lo queria hacer, pero no se q logo poner

por ejemplo tengo el q hice pero se q warrior no le gusta, el normal no lo quiero sobreexplotar, etc

**Comment by Mishi04** [comment]
usa el de laida kpo, es simple, fachero y lo hizo laida osea buenardo

**Comment by Mapeadoh** [comment]
XD ok ahi lo pongo

**Comment by Mishi04** [comment]
weno cierro esto
