### ISSUE TITLE
ozark skid

### ISSUE THREAD

**Issue by ProfKambing** [WarriorCrystal/Huzuniplus-2#6]

**Comment by Mapeadoh** [comment]
proof

**Comment by WarriorCrystal** [comment]
ozark? whats that lol idk i don't play anarchy too much

**Comment by WarriorCrystal** [comment]
50% of ozark modules are from cheatbreakerplus so are my own modules

**Comment by Mapeadoh** [comment]
se copian del luis y romper obsidiana
