### ISSUE TITLE
###############################################

### ISSUE THREAD

**Issue by Francescounv2** [WarriorCrystal/Huzuniplus-2#8]
[Estribillo: Duki]
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras
Duko gana cuando lo nombran
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras
Duko gana cuando lo nombran

[Verso 1: Moonkey]
Yah, cara tatuada, mira mi cuello (Cara tatuada), parece azúcar, bebé
Salgo a buscarte, voy a 300 por la autopista, bebé (Voy ya)
Muévete, sal de la barra, muévelo lento, bebé
Muévete, súbete encima de la tarima, bebé (Subete, yo')
Muévelo (Muévelo), que son las tres de la mañana y no te he visto (Visto)
Llévame al baño, baby, que no me resisto (Uh-uh-uh; -sisto)
Con tus amigas, que si quieren las invito (Las invito)
Las invito yo

[Estribillo: Duki & WE$T DUBAI]
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras
Duko gana cuando lo nombran
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras (Uah)
Duko gana cuando lo nombran
[Verso 2: WE$T DUBAI]
Voy dos colore' (Voy dos colore'), woh
En el party, pastilla' de colore' (Pastilla' de colore'), woh
'Toy con puta' de colore' (Con puta' de colore', yeah), woh
Diferentes colore' (Diferente' colore')
'Toy gastando los colore' (Colore', colore')
Baby, no te enamore' (No te enamore')
Vamo' a gastar los colore' (Los colore')
Tengo swag de dos colore' (Dos colore')
En el party con pastilla' de colore' (De colore'), woh
Baby, no te enamore'
Vamo' a gastar los colore'
Tengo swag de dos colore'
En el party con pastilla' de colore', woh

[Puente: WE$T DUBAI]
Baby, muévete (Muévete)
Baby, muévete (Muévete)
Muévete (Muévete)
Muéve-Muévete (Muévete)
Muéve-Muévete (Muévete)
Muéve-Muévete (Muévete)
Baby, muévete (Muévete)
Muévete, muévete, eh, eh, eh (Eh-eh-eh)

[Estribillo: Duki]
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras
Duko gana cuando lo nombran
Mmm, yo', muévete antes de que el suelo se rompa
Mmm, yo', muévete antes que la luna se esconda
Mmm, yo', muévete, odio que me tapen la sombra
Amo que se coman mis sobras
Duko gana cuando lo nombran

**Comment by Mapeadoh** [comment]
no te voy a desmutear

**Comment by Francescounv2** [comment]
fan de spreen

**Comment by Mapeadoh** [comment]
eres tu

**Comment by Mapeadoh** [comment]
---------------------------

**Comment by Francescounv2** [comment]
humilla

**Comment by Mapeadoh** [comment]
gei

**Comment by Francescounv2** [comment]
eres

**Comment by Mapeadoh** [comment]
tu

**Comment by Mapeadoh** [comment]
--------------

**Comment by Francescounv2** [comment]
tu si yo no

**Comment by Mapeadoh** [comment]
tarde L

**Comment by Francescounv2** [comment]
@TripleX

**Comment by Mapeadoh** [comment]
@everyone

**Comment by ghost** [comment]
sex

**Comment by Mapeadoh** [comment]
nunca vas a tener

**Comment by Mapeadoh** [comment]
------------------------------

**Comment by ghost** [comment]
bloddy man

**Comment by Mapeadoh** [comment]
:miedo:

**Comment by ghost** [comment]
No perra

**Comment by Mapeadoh** [comment]
si nene

**Comment by ghost** [comment]
No baby

**Comment by Mapeadoh** [comment]
si papi

**Comment by afk821** [comment]
Hagamos hijos (no homo)

**Comment by Mapeadoh** [comment]
gei q eres

**Comment by Mapeadoh** [comment]
———————————————

**Comment by ghost** [comment]
tú

**Comment by Mapeadoh** [comment]
todos geis menos yo
